CREATE TABLE "aircraft_models" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"model" text NOT NULL,
	"aliases" text,
	"is_fixed_wing" boolean NOT NULL,
	"is_helicopter" boolean NOT NULL,
	"is_single_engine" boolean NOT NULL,
	"is_turbine" boolean NOT NULL,
	"is_military" boolean NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL
);
--> statement-breakpoint
CREATE TABLE "flight_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" text NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp NOT NULL,
	"DATE_TIME" timestamp NOT NULL,
	"AIRCRAFT_TYPE" text NOT NULL,
	"AIRCRAFT_ID" text,
	"FROM" text,
	"ROUTE" text,
	"TO" text,
	"OUT" text,
	"IN" text,
	"TOTAL_TIME" numeric NOT NULL,
	"SINGLE_ENGINE" numeric,
	"MULTI_ENGINE" numeric,
	"FIXED_WING" numeric,
	"TURBINE" numeric,
	"FIXED_WING_MULTI_ENGINE" numeric,
	"FIXED_WING_TURBINE" numeric,
	"PIC" numeric,
	"FIXED_WING_PIC" numeric,
	"FIXED_WING_TURBINE_PIC" numeric,
	"SIC" numeric,
	"DUAL_GIVEN" numeric,
	"XC" numeric,
	"NIGHT" numeric,
	"NIGHT_UNAIDED" numeric,
	"NVS" numeric,
	"NVG" numeric,
	"SIM_INST" numeric,
	"DUAL_RCVD" numeric,
	"ACTUAL_INST" numeric,
	"SIMULATOR" numeric,
	"INSTRUCTOR" numeric,
	"DAY_T/O" integer,
	"DAY_LDG" integer,
	"NIGHT_T/O" integer,
	"NIGHT_LDG" integer,
	"ARR" integer,
	"T&G" integer,
	"BOL" integer,
	"FCL" integer,
	"SEA/LAND" text,
	"CATAPULT" integer,
	"SOLO" numeric,
	"DAYSYSTEM" numeric,
	"WEATHER" numeric,
	"HOOD" numeric,
	"SES" numeric,
	"MES" numeric,
	"TAXI" numeric,
	"COMPLEX" numeric,
	"CUSTOM" numeric,
	"TAILDRAGGER" numeric,
	"INSTRUMENT_APPROACH" integer,
	"PRECISION_APPROACH" integer,
	"NON_PRECISION_APPROACH" integer,
	"AIRCRAFT_COMMANDER" numeric,
	"SPECIAL_CREW_TIME" numeric,
	"COMBAT_SORTIES" integer,
	"SORTIES" integer,
	"COMBAT" numeric,
	"MISSION_COMMANDER" numeric,
	"CIVILIAN_OTHER" numeric,
	"TOT" numeric,
	"OT" numeric,
	"OTR" numeric,
	"ORT" numeric,
	"SART" numeric,
	"C/S_SRT" integer,
	"HELO" numeric,
	"MILITARY" numeric
);
