export const mockAggregates = {
  totalFixedWingMultiEngineHours: 250.5,
  totalMilitaryHours: 120.0,
  totalFixedWingPilotInCommandHours: 300.0,
  totalPilotInCommandHours: 450.0,
  totalFixedWingTurbineHours: 200.0,
  totalHours: 600.0,
  totalFixedWingTurbinePilotInCommand1000Hours: 150.0,
  totalTurbine1500Hours: 100.0,
  totalFixedWingTurbine1000Hours: 180.0,
  total12MonthHours: 80.0,
  total24MonthHours: 150.0,
  total36MonthHours: 220.0,
  flightAggregatesPerAircraft: [
    {
      aircraftType: "Cessna 172",
      totalHours: 200.0,
      totalSingleEngineHours: 200.0,
      totalMultiEngineHours: 0.0,
      totalHelicopterHours: 0.0,
      totalDayLandings: 150,
      totalNightLandings: 20,
      totalNightHours: 30.0,
      totalInstrumentHours: 25.0,
      totalSimulatedInstrumentHours: 15.0,
      totalInstrumentApproaches: 10,
      totalCrossCountryHours: 100.0,
      totalSoloHours: 50.0,
      totalPilotInCommandHours: 150.0,
      totalSecondInCommandHours: 0.0,
      totalDualReceivedHours: 20.0,
      totalInstructorHours: 10.0,
      totalSorties: 5,
      totalSpecialFlightCrewHours: 0.0,
      totalNightVisionGoggleHours: 0.0,
    },
    {
      aircraftType: "Boeing 737",
      totalHours: 300.0,
      totalSingleEngineHours: 0.0,
      totalMultiEngineHours: 300.0,
      totalHelicopterHours: 0.0,
      totalDayLandings: 100,
      totalNightLandings: 50,
      totalNightHours: 60.0,
      totalInstrumentHours: 40.0,
      totalSimulatedInstrumentHours: 20.0,
      totalInstrumentApproaches: 15,
      totalCrossCountryHours: 200.0,
      totalSoloHours: 0.0,
      totalPilotInCommandHours: 250.0,
      totalSecondInCommandHours: 50.0,
      totalDualReceivedHours: 0.0,
      totalInstructorHours: 0.0,
      totalSorties: 10,
      totalSpecialFlightCrewHours: 5.0,
      totalNightVisionGoggleHours: 2.0,
    },
    {
      aircraftType: "Bell 206",
      totalHours: 100.0,
      totalSingleEngineHours: 0.0,
      totalMultiEngineHours: 0.0,
      totalHelicopterHours: 100.0,
      totalDayLandings: 80,
      totalNightLandings: 10,
      totalNightHours: 15.0,
      totalInstrumentHours: 5.0,
      totalSimulatedInstrumentHours: 5.0,
      totalInstrumentApproaches: 3,
      totalCrossCountryHours: 50.0,
      totalSoloHours: 20.0,
      totalPilotInCommandHours: 50.0,
      totalSecondInCommandHours: 0.0,
      totalDualReceivedHours: 30.0,
      totalInstructorHours: 10.0,
      totalSorties: 8,
      totalSpecialFlightCrewHours: 0.0,
      totalNightVisionGoggleHours: 5.0,
    },
  ],
};
